old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            read_write_timeout: 4
            heartbeat: 2
    producers:
        messaging:
            class: App\Rabbit\MessagingProducer
            connection:       default
            exchange_options: { name: 'qMessages', type: direct }
        processing:
            class: App\Rabbit\Processing\ProcessingProducer
            connection:       default
            exchange_options: {name: 'qProcessing', type: direct}
    consumers:
        messaging:
            connection:       default
            exchange_options: { name: 'qMessages', type: direct }
            queue_options:    { name: 'qMessages'}
            callback:         message_service
            enable_logger:    true
        processing:
            connection:       default
            exchange_options: { name: 'qProcessing', type: direct}
            queue_options:    { name: 'qProcessing'}
            callback:         processing_service
            enable_logger:    true